import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import NavBar from "@/components/HeroSection/NavBar";
import localFont from "next/font/local";

const sequel100 = localFont({
  src: [
    {
      path: "../../public/fonts/Sequel100Black-65.ttf",
      weight: "300",
      style: "light",
    },
    {
      path: "../../public/fonts/Sequel100Black-75.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Sequel100Black-85.ttf",
      weight: "500",
      style: "medium",
    },
    {
      path: "../../public/fonts/Sequel100Black-95.ttf",
      weight: "600",
      style: "semibold",
    },
    {
      path: "../../public/fonts/Sequel100Black-105.ttf",
      weight: "700",
      style: "bold",
    },
    {
      path: "../../public/fonts/Sequel100Black-115.ttf",
      weight: "800",
      style: "black",
    },
  ],
  variable: "--font-sequel100",
  display: "swap",
});

const inter = Inter({
  variable: "--Intert",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "100", "200", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const massages = await getMessages();
  return (
    <NextIntlClientProvider messages={massages}>
      <html lang="en">
        <body className={`${sequel100.variable} ${inter.variable} antialiased`}>
          <NavBar />
          {children}
        </body>
      </html>
    </NextIntlClientProvider>
  );
}
